before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp .env.example .env
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database "urkel_test";' -U postgres
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.1.4
addons:
  postgresql: "9.3"
deploy:
  provider: heroku
  run: "rake db:migrate"
  app:
    master: urkel-staging
    production: urkel
